version: "1.0"
stages:
  - "clone"
  - "build"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "jafow/jafow-blog"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: build
    description: build
    stage: build
    type: build
    dockerfile: Dockerfile
    image_name: jafow/jafow-blog
    tag: "${{CF_SHORT_REVISION}}"
  deploy:
    image: "${{build}}"
    title: deploy
    description: deploy
    stage: build
    commands:
      - mkdir -p .ssh
      - ssh-keyscan -H "${HOST}" >> .ssh/known_hosts
      - echo "${SSH_KEY}" | tr \'"${SPLIT_CHAR}"\' '\n' > .ssh/gh-deploy
      - chmod 600 .ssh/gh-deploy
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > .ssh/config
      - hugo
      - rsync -az -O --delete public -e 'ssh -i .ssh/gh-deploy' gh-deploy@${HOST}:/var/www/very-good-website.xyz/
