baseUrl = "/"
languageCode = "en-us"
title = "jafow blog"
theme = "accessible-minimalism"
relativeURLs = true
canonifyURLs = true
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
